const mongoose = require('mongoose');
const Course = require('../../src/models/Course');
const User = require('../../src/models/User');
const { COURSE_CATEGORIES, COURSE_LEVELS, COURSE_STATUS } = require('../../src/utils/constants');

describe('Course Model', () => {
  let instructor;

  beforeAll(async () => {
    await mongoose.connect(process.env.MONGODB_URI_TEST || 'mongodb://localhost:27017/coursecreator_test', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
  });

  afterAll(async () => {
    await mongoose.connection.dropDatabase();
    await mongoose.connection.close();
  });

  beforeEach(async () => {
    await Course.deleteMany({});
    await User.deleteMany({});

    // Create instructor user
    instructor = new User({
      username: 'courseinstructor',
      email: 'instructor@example.com',
      password: 'password123',
      role: 'instructor'
    });
    await instructor.save();
  });

  describe('Course Creation', () => {
    it('should create a course successfully', async () => {
      const courseData = {
        title: 'Test Course',
        description: 'This is a test course description',
        category: COURSE_CATEGORIES.WEB,
        level: COURSE_LEVELS.BEGINNER,
        instructor: instructor._id,
        modules: [
          {
            title: 'Module 1',
            order: 1,
            lessons: [
              {
                title: 'Lesson 1',
                content: 'Lesson content',
                order: 1,
                duration: 30
              }
            ]
          }
        ]
      };

      const course = new Course(courseData);
      await course.save();

      expect(course._id).toBeDefined();
      expect(course.title).toBe(courseData.title);
      expect(course.description).toBe(courseData.description);
      expect(course.category).toBe(courseData.category);
      expect(course.level).toBe(courseData.level);
      expect(course.instructor.toString()).toBe(instructor._id.toString());
      expect(course.status).toBe(COURSE_STATUS.DRAFT);
      expect(course.stats.totalLessons).toBe(1);
      expect(course.stats.totalDuration).toBe(30);
    });

    it('should create AI-generated course', async () => {
      const courseData = {
        title: 'AI Generated Course',
        description: 'This course was generated by AI',
        category: COURSE_CATEGORIES.AI_ML,
        instructor: instructor._id,
        aiConfig: {
          creativityLevel: 8,
          contentDepth: 9,
          courseStyle: 'modern',
          generationType: 'trending'
        },
        aiGenerated: {
          isGenerated: true,
          model: 'gpt-4',
          prompt: 'Create a course about AI trends',
          generationTime: new Date()
        }
      };

      const course = new Course(courseData);
      await course.save();

      expect(course.aiGenerated.isGenerated).toBe(true);
      expect(course.aiGenerated.model).toBe('gpt-4');
      expect(course.aiConfig.generationType).toBe('trending');
    });

    it('should validate required fields', async () => {
      const course = new Course({
        // Missing required fields
        instructor: instructor._id
      });

      await expect(course.save()).rejects.toThrow();
    });
  });

  describe('Course Methods', () => {
    let course;

    beforeEach(async () => {
      course = new Course({
        title: 'Test Course for Methods',
        description: 'Testing course methods',
        category: COURSE_CATEGORIES.WEB,
        instructor: instructor._id,
        modules: [
          {
            title: 'Module 1',
            order: 1,
            lessons: [
              { title: 'Lesson 1', content: 'Content 1', order: 1, duration: 30 },
              { title: 'Lesson 2', content: 'Content 2', order: 2, duration: 45 }
            ]
          }
        ]
      });
      await course.save();
    });

    it('should calculate virtual fields correctly', () => {
      expect(course.totalDuration).toBe(75);
      expect(course.totalLessonsCount).toBe(2);
    });

    it('should update stats on save', async () => {
      // Add another lesson
      course.modules[0].lessons.push({
        title: 'Lesson 3',
        content: 'Content 3',
        order: 3,
        duration: 60
      });

      await course.save();

      expect(course.stats.totalLessons).toBe(3);
      expect(course.stats.totalDuration).toBe(135);
    });

    it('should mark as AI generated', async () => {
      await course.generateAIContent('Create advanced web development content', {
        creativity: 8,
        depth: 9
      });

      expect(course.aiGenerated.isGenerated).toBe(true);
      expect(course.aiGenerated.prompt).toBe('Create advanced web development content');
      expect(course.aiGenerated.generationTime).toBeDefined();
    });
  });

  describe('Course Statics', () => {
    beforeEach(async () => {
      // Create test courses
      await Course.create([
        {
          title: 'Trending Course 1',
          description: 'A trending course',
          category: COURSE_CATEGORIES.WEB3,
          instructor: instructor._id,
          isPublished: true,
          stats: { enrolledStudents: 150, averageRating: 4.7 },
          aiConfig: { generationType: 'trending' },
          aiGenerated: { isGenerated: true }
        },
        {
          title: 'Trending Course 2',
          description: 'Another trending course',
          category: COURSE_CATEGORIES.AI_ML,
          instructor: instructor._id,
          isPublished: true,
          stats: { enrolledStudents: 200, averageRating: 4.9 },
          aiConfig: { generationType: 'trending' },
          aiGenerated: { isGenerated: true }
        },
        {
          title: 'Rare Course',
          description: 'A rare skills course',
          category: COURSE_CATEGORIES.CYBERSECURITY,
          instructor: instructor._id,
          isPublished: true,
          aiConfig: { generationType: 'rare' },
          aiGenerated: { isGenerated: true }
        },
        {
          title: 'Draft Course',
          description: 'Unpublished course',
          category: COURSE_CATEGORIES.WEB,
          instructor: instructor._id,
          isPublished: false
        }
      ]);
    });

    it('should find trending courses', async () => {
      const trendingCourses = await Course.findTrending(2);

      expect(trendingCourses).toHaveLength(2);
      expect(trendingCourses[0].title).toBe('Trending Course 2'); // More students
      expect(trendingCourses[1].title).toBe('Trending Course 1');
      expect(trendingCourses[0].isPublished).toBe(true);
    });

    it('should find courses by AI type', async () => {
      const trendingCourses = await Course.findByAIType('trending');
      const rareCourses = await Course.findByAIType('rare');

      expect(trendingCourses).toHaveLength(2);
      expect(rareCourses).toHaveLength(1);
      expect(rareCourses[0].title).toBe('Rare Course');
    });
  });

  describe('Course Module and Lesson Management', () => {
    let course;

    beforeEach(async () => {
      course = new Course({
        title: 'Module Test Course',
        description: 'Testing modules and lessons',
        category: COURSE_CATEGORIES.WEB,
        instructor: instructor._id
      });
    });

    it('should add modules with lessons', async () => {
      course.modules.push({
        title: 'New Module',
        order: 1,
        lessons: [
          {
            title: 'New Lesson',
            content: 'Lesson content',
            order: 1,
            duration: 30
          }
        ]
      });

      await course.save();

      expect(course.modules).toHaveLength(1);
      expect(course.modules[0].lessons).toHaveLength(1);
      expect(course.modules[0].title).toBe('New Module');
      expect(course.modules[0].lessons[0].title).toBe('New Lesson');
    });

    it('should handle AI-generated modules', async () => {
      course.modules.push({
        title: 'AI Generated Module',
        order: 1,
        aiGenerated: {
          isGenerated: true,
          model: 'gpt-4',
          prompt: 'Generate module about web fundamentals'
        },
        lessons: [
          {
            title: 'AI Lesson',
            content: 'AI generated content',
            order: 1,
            aiGenerated: {
              isGenerated: true,
              model: 'gpt-4',
              prompt: 'Generate lesson content'
            }
          }
        ]
      });

      await course.save();

      expect(course.modules[0].aiGenerated.isGenerated).toBe(true);
      expect(course.modules[0].lessons[0].aiGenerated.isGenerated).toBe(true);
    });
  });
});
